cycle_scheme:
  1:
    [[5, .4],
     [5, .5],
     [3, .6],
     [5, .65],
     [5, .75],
     [5+, .85],
     [5, .75],
     [5+, .65]]
  2:
    [[5, .4],
     [5, .5],
     [3, .6],
     [3, .7],
     [3, .8],
     [3+, .9],
     [3, .8],
     [3+, .7]]
  3:
    [[5, .4],
     [5, .5],
     [3, .6],
     [5, .75],
     [3, .85],
     [1+, .95],
     [3, .85],
     [5+, .75]]
  4:
    [[5, .4],
     [5, .5],
     [5, .6]]

accessory_scheme:
  press:
    dips:
      reps: 15
      sets: 5
    chinups:
      reps: 10
      sets: 5
  deadlift:
    good_morning:
      reps: 12
      sets: 5
    hanging_leg_raise:
      reps: 15
      sets: 5
  bench_press:
    dumbbell_bench:
      reps: 15
      sets: 5
      weight: 47.5
    hanging_leg_raise:
      reps: 10
      sets: 5
      weight: 75
  squat:
    leg_press:
      reps: 15
      sets: 5
      weight: 315
    leg_curl:
      reps: 10
      sets: 5
      weight: 85

workout_order: ['press', 'deadlift', 'bench_press', 'squat']
