require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SubcyclesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Subcycle. As you add validations to Subcycle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubcyclesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all subcycles as @subcycles" do
      subcycle = Subcycle.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:subcycles)).to eq([subcycle])
    end
  end

  describe "GET show" do
    it "assigns the requested subcycle as @subcycle" do
      subcycle = Subcycle.create! valid_attributes
      get :show, {:id => subcycle.to_param}, valid_session
      expect(assigns(:subcycle)).to eq(subcycle)
    end
  end

  describe "GET new" do
    it "assigns a new subcycle as @subcycle" do
      get :new, {}, valid_session
      expect(assigns(:subcycle)).to be_a_new(Subcycle)
    end
  end

  describe "GET edit" do
    it "assigns the requested subcycle as @subcycle" do
      subcycle = Subcycle.create! valid_attributes
      get :edit, {:id => subcycle.to_param}, valid_session
      expect(assigns(:subcycle)).to eq(subcycle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Subcycle" do
        expect {
          post :create, {:subcycle => valid_attributes}, valid_session
        }.to change(Subcycle, :count).by(1)
      end

      it "assigns a newly created subcycle as @subcycle" do
        post :create, {:subcycle => valid_attributes}, valid_session
        expect(assigns(:subcycle)).to be_a(Subcycle)
        expect(assigns(:subcycle)).to be_persisted
      end

      it "redirects to the created subcycle" do
        post :create, {:subcycle => valid_attributes}, valid_session
        expect(response).to redirect_to(Subcycle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subcycle as @subcycle" do
        post :create, {:subcycle => invalid_attributes}, valid_session
        expect(assigns(:subcycle)).to be_a_new(Subcycle)
      end

      it "re-renders the 'new' template" do
        post :create, {:subcycle => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested subcycle" do
        subcycle = Subcycle.create! valid_attributes
        put :update, {:id => subcycle.to_param, :subcycle => new_attributes}, valid_session
        subcycle.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested subcycle as @subcycle" do
        subcycle = Subcycle.create! valid_attributes
        put :update, {:id => subcycle.to_param, :subcycle => valid_attributes}, valid_session
        expect(assigns(:subcycle)).to eq(subcycle)
      end

      it "redirects to the subcycle" do
        subcycle = Subcycle.create! valid_attributes
        put :update, {:id => subcycle.to_param, :subcycle => valid_attributes}, valid_session
        expect(response).to redirect_to(subcycle)
      end
    end

    describe "with invalid params" do
      it "assigns the subcycle as @subcycle" do
        subcycle = Subcycle.create! valid_attributes
        put :update, {:id => subcycle.to_param, :subcycle => invalid_attributes}, valid_session
        expect(assigns(:subcycle)).to eq(subcycle)
      end

      it "re-renders the 'edit' template" do
        subcycle = Subcycle.create! valid_attributes
        put :update, {:id => subcycle.to_param, :subcycle => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subcycle" do
      subcycle = Subcycle.create! valid_attributes
      expect {
        delete :destroy, {:id => subcycle.to_param}, valid_session
      }.to change(Subcycle, :count).by(-1)
    end

    it "redirects to the subcycles list" do
      subcycle = Subcycle.create! valid_attributes
      delete :destroy, {:id => subcycle.to_param}, valid_session
      expect(response).to redirect_to(subcycles_url)
    end
  end

end
